# Generated by Django 2.2.5 on 2019-09-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='text',
            field=models.TextField(max_length=160),
        ),
    ]
