# Generated by Django 2.2.5 on 2019-09-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_auto_20190914_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=50)),
                ('lon', models.CharField(max_length=50)),
            ],
        ),
    ]
