# Generated by Django 2.2.5 on 2019-09-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0005_auto_20190915_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorinfo',
            name='ip',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visitorinfo',
            name='lat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visitorinfo',
            name='lon',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
